version: "3.7"

services:

  proxy:
    build:
      context: ./proxy
    command: ["./wait-for-it.sh", "--timeout=0", "ehr-integration_webapp_1:3003", "--", "nginx", "-g", "daemon off;"]
    tty: true
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - webapp
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html

  webapp:
    build:
      context: .
    depends_on:
      - mariadb
    environment:
      - MESSAGE_PASSER_ADDRESS=danvers
      # - DEVICE_ADDRESS=stacy
      - DEVICE_ADDRESS=device.consultproject.co.uk
      # ~MDC Not a huge fan of direct communication between grey and danvers, but enabled at present.
      - NODE_EXTRA_CA_CERTS=/consult.crt
    extra_hosts:
      # ~MDC Not a huge fan of direct communication between grey and danvers, but enabled at present.
      danvers: 10.0.1.10

  migration:
    image: ehr-integration_webapp:latest
    command: ["./wait-for-it.sh", "--timeout=0", "ehr-integration_mariadb_1:3306", "--", "npm", "run", "migrate"]
    depends_on:
      - webapp
      - mariadb

  mariadb:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ehr_data_volume:/var/lib/mysql

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - proxy
    command: certonly --webroot --webroot-path=/var/www/html --email martin.chapman@kcl.ac.uk --agree-tos --no-eff-email --force-renewal -d ehr.consultproject.co.uk

volumes:
  ehr_data_volume:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  default:
    external:
      name: ehr_network
