version: "3.7"

services:

  proxy:
    build:
      context: ./proxy
    command: ["./wait-for-it.sh", "--timeout=0", "ehr-integration_webapp_1:3003", "--", "nginx", "-g", "daemon off;"]
    tty: true
    ports:
      - '3003:443'

  webapp:
    build:
      context: .
    depends_on:
      - mysql
    environment:
      - MESSAGE_PASSER_ADDRESS=danvers:3005
      - DEVICE_ADDRESS=stacy:3000
    extra_hosts:
      - danvers:172.21.0.1
      - stacy:172.18.0.1

  migration:
    image: ehr-integration_webapp:latest
    command: ["./wait-for-it.sh", "--timeout=0", "ehr-integration_mysql_1:3306", "--", "npm", "run", "migrate"]
    links:
      - webapp
      - mysql

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ehr_data_volume:/var/lib/mysql

volumes:
  ehr_data_volume:

networks:
  default:
    external:
      name: ehr_network
