version: "3.7"

services:

  webapp:
    build:
      context: .
    depends_on:
      - mysql

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ehr_data_volume:/var/lib/mysql

  migration:
    image: ehr-integration_webapp:latest
    command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "migrate"]
    links:
      - mysql
    depends_on:
      - mysql

  proxy:
    build:
      context: ./proxy
    tty: true
    ports:
      - '443:443'
      - '80:80'

volumes:
  ehr_data_volume:

networks:
  default:
    external:
      name: network
