version: "3.7"

services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.demo
    command: ["./wait-for-it.sh", "--timeout=0", "ehr-integration_webapp_1:3003", "--", "nginx", "-g", "daemon off;"]
    tty: true
    ports:
      - '3003:443'

  webapp:
    build:
      context: .
    depends_on:
      - mariadb
    environment:
      MESSAGE_PASSER_ADDRESS: ${MESSAGE_PASSER_ADDRESS_DEMO}
      DEVICE_ADDRESS: ${DEVICE_ADDRESS_DEMO}

  migration:
    image: ehr-integration_webapp:latest
    command: ["./wait-for-it.sh", "--timeout=0", "ehr-integration_mariadb_1:3306", "--", "npm", "run", "migrate"]
    depends_on:
      - webapp
      - mariadb

  mariadb:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ehr_data_volume:/var/lib/mysql

volumes:
  ehr_data_volume:

networks:
  default:
    external:
      name: ehr_network
